
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
  port: 8082

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always


  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2_db

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver